version: "3.9"

services:
  postgres:
    image: docker.io/library/postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_POSTGRESDB_DATABASE}
      POSTGRES_USER: ${DB_POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:Z
    ports:
      - "5432:5432"

  adminer:
    image: docker.io/adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  n8n:
    image: docker.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    volumes:
      - n8n_data:/home/node/.n8n

  ngrok:
    image: docker.io/wernight/ngrok
    depends_on:
      - n8n
    environment:
      NGROK_PORT: "${N8N_PORT}"
      NGROK_AUTHTOKEN: "${NGROK_AUTH_TOKEN}"
      NGROK_HOST: 0.0.0.0
    ports:
      - "4040:4040"
    command: "http n8n:${N8N_PORT}"
    restart: unless-stopped

volumes:
  pg_data:
  n8n_data: